RabbitMQ: Use durable queues
While sample works with docker image `rabbitmq:3-management`, it fails with `rabbitmq:latest`:

> RabbitMQ.Client.Exceptions.OperationInterruptedException: 'The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=541, text='INTERNAL_ERROR - Feature `transient_nonexcl_queues` is deprecated.
By default, this feature is not permitted anymore.
The feature will be removed from a future major RabbitMQ version, regardless of the configuration; actual version to be determined.
To...', classId=50, methodId=10'